server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: demo_app
          # etiqueta personalizada
          app: demo
          # ruta en el contenedor; promtail en este compose monta ./logs -> /var/log/app
          __path__: /var/log/app/*.log
